const seedbaleData = {
  categories: [
    { name: "Burgers", description: "Juicy grilled burgers" },
    { name: "Pizzas", description: "Oven-baked cheesy pizzas" },
    { name: "Burritos", description: "Rolled Mexican delights" },
    { name: "Sandwiches", description: "Stacked and stuffed sandwiches" },
    { name: "Wraps", description: "Rolled up wraps packed with flavor" },
    { name: "Bowls", description: "Balanced rice and protein bowls" },
  ],

  customizations: [
    // Sides
    { icon: "🍟", name: "Fries", price: 1.49, type: "side" },
    { icon: "🥗", name: "Garden Salad", price: 2.99, type: "side" },
    { icon: "🧅", name: "Onions", price: 2.75, type: "side" },
    { icon: "🥤", name: "Coke", price: 1.5, type: "side" },
    { icon: "🍦", name: "Vanilla Soft Serve", price: 1.99, type: "side" },
    { icon: "🫙", name: "Coleslaw Cup", price: 1.25, type: "side" },
    { icon: "🧋", name: "Iced Tea", price: 4, type: "side" },
    { icon: "🥗", name: "Salad", price: 5, type: "side" },
    { icon: "🌽", name: "Sweet Corn", price: 1, type: "side" },
    { icon: "🍰", name: "Choco Lava Cake", price: 5.5, type: "side" },

    // Toppings
    { icon: "🧀", name: "Extra Cheese", price: 1.25, type: "topping" },
    { icon: "🥩", name: "Extra Meat Patty", price: 5.25, type: "topping" },
    { icon: "🥑", name: "Avocado", price: 1.75, type: "topping" },
    { icon: "🥓", name: "Bacon", price: 2.5, type: "topping" },
    { icon: "🌶️", name: "Jalapeños", price: 1, type: "topping" },
    { icon: "🍳", name: "Fried Egg", price: 1.0, type: "topping" },
    { icon: "🍅", name: "Tomatoes", price: 1.0, type: "topping" },

    { icon: "🥖", name: "Garlic Bread", price: 1.2, type: "side" },
    { icon: "NA", name: "Chicken Nuggets", price: 3, type: "side" },
    { icon: "🫒", name: "Olives", price: 2.4, type: "side" },
    { icon: "NA", name: "Mozzarella Sticks", price: 1.5, type: "side" },
  ],

  menu: [
    {
      name: "Classic Cheeseburger",
      description: "Beef patty, cheese, lettuce, tomato",
      image_url:
        "https://images.pexels.com/photos/3915915/pexels-photo-3915915.jpeg",
      price: 25.99,
      rating: 4.5,
      calories: 550,
      size: [
        { name: "regular", price: 25.99, calories: 550, isDefault: true, protein : 50 },
      ],
      protein: 25,
      category_name: "Burgers",
      customizations: ["Extra Cheese", "Coke", "Fries", "Onions", "Bacon"],
    },
    {
      name: "Pepperoni Pizza",
      description: "Loaded with cheese and pepperoni slices",
      image_url:
        "https://images.pexels.com/photos/17907810/pexels-photo-17907810.jpeg",
      price: 30.99,
      rating: 4.7,
      calories: 700,
      protein: 30,
      category_name: "Pizzas",
      size: [
        { name: "small", price: 25.99, calories: 550, isDefault: true, protein : 50  },
        { name: "medium", price: 30.99, calories: 850, isDefault: false, protein : 50  },
        { name: "large", price: 34.99, calories: 1050, isDefault: false, protein : 50  },
        { name: "extra-large", price: 40.99, calories: 1550, isDefault: false, protein : 50  },
      ],
      customizations: [
        "Extra Cheese",
        "Jalapeños",
        "Garlic Bread",
        "Coke",
        "Olives",
      ],
    },
    {
      name: "Bean Burrito",
      description: "Stuffed with beans, rice, salsa",
      image_url:
        "https://images.pexels.com/photos/27365284/pexels-photo-27365284.jpeg",
      price: 20.99,
      rating: 4.2,
      calories: 480,
      protein: 18,
      category_name: "Burritos",
      size: [
        { name: "small", price: 20.99, calories: 480, isDefault: true, protein : 50  },
        { name: "medium", price: 25.99, calories: 850, isDefault: false, protein : 50  },
        { name: "large", price: 30.99, calories: 1050, isDefault: false, protein : 50  },
        { name: "extra-large", price: 34.99, calories: 1550, isDefault: false, protein : 50  },
      ],
      customizations: ["Jalapeños", "Iced Tea", "Fries", "Salad"],
    },
    {
      name: "BBQ Bacon Burger",
      description: "Smoky BBQ sauce, crispy bacon, cheddar",
      image_url:
        "https://images.pexels.com/photos/31450804/pexels-photo-31450804.jpeg",
      price: 27.5,
      rating: 4.8,
      calories: 650,
      protein: 29,
      category_name: "Burgers",
      size: [{ name: "regular", price: 27.5, calories: 650, isDefault: true, protein : 50  }],
      customizations: ["Onions", "Fries", "Coke", "Bacon", "Avocado"],
    },
    {
      name: "Chicken Caesar Wrap",
      description: "Grilled chicken, lettuce, Caesar dressing",
      image_url:
        "https://images.pexels.com/photos/9624298/pexels-photo-9624298.jpeg",
      price: 21.5,
      rating: 4.4,
      calories: 490,
      protein: 28,
      category_name: "Wraps",
      size: [
        { name: "small", price: 25.99, calories: 490, isDefault: true, protein : 50  },
        { name: "medium", price: 30.99, calories: 890, isDefault: false, protein : 50  },
        { name: "large", price: 34.99, calories: 1190, isDefault: false, protein : 50  },
      ],
      customizations: ["Extra Cheese", "Coke", "Olives", "Tomatoes"],
    },
    {
      name: "Grilled Veggie Sandwich",
      description: "Roasted veggies, pesto, cheese",
      image_url:
        "https://images.pexels.com/photos/28681955/pexels-photo-28681955.jpeg",
      price: 19.99,
      rating: 4.1,
      calories: 420,
      protein: 19,
      category_name: "Sandwiches",
      size: [
        { name: "regular", price: 25.99, calories: 550, isDefault: true, protein : 50  },
        { name: "large", price: 34.99, calories: 1050, isDefault: false, protein : 50  },
      ],
      customizations: ["Olives", "Coke", "Iced Tea"],
    },
    {
      name: "Double Patty Burger",
      description: "Two juicy beef patties and cheese",
      image_url:
        "https://images.pexels.com/photos/11062006/pexels-photo-11062006.jpeg",
      price: 32.99,
      rating: 4.9,
      calories: 720,
      protein: 35,
      category_name: "Burgers",
      size: [{ name: "regular", price: 32.99, calories: 720, isDefault: true, protein : 50  }],
      customizations: [
        "Extra Cheese",
        "Onions",
        "Fries",
        "Coke",
        "Chicken Nuggets",
      ],
    },
    {
      name: "Paneer Tikka Pizza",
      description: "Spicy paneer, mint chutney, veggies",
      image_url:
        "https://images.pexels.com/photos/11974635/pexels-photo-11974635.jpeg",
      price: 23.99,
      rating: 4.6,
      calories: 470,
      protein: 20,
      category_name: "Wraps",
      size: [
        { name: "small", price: 23.99, calories: 490, isDefault: true, protein : 50  },
        { name: "medium", price: 29.99, calories: 890, isDefault: false, protein : 50  },
        { name: "large", price: 32.99, calories: 1190, isDefault: false, protein : 50  },
      ],
      customizations: ["Jalapeños", "Tomatoes", "Salad", "Fries", "Iced Tea"],
    },
    {
      name: "Mexican Taco Tray",
      description: "Rice, beans, corn, guac, salsa",
      image_url:
        "https://images.pexels.com/photos/674578/pexels-photo-674578.jpeg",
      price: 26.49,
      rating: 4.7,
      calories: 610,
      protein: 24,
      category_name: "Bowls",
      size: [
        { name: "small", price: 25.99, calories: 490, isDefault: true, protein : 50  },
        { name: "medium", price: 30.99, calories: 890, isDefault: false, protein : 50  },
        { name: "large", price: 34.99, calories: 1190, isDefault: false, protein : 50  },
      ],
      customizations: ["Avocado", "Sweet Corn", "Salad", "Iced Tea"],
    },
    {
      name: "Spicy Chicken Burger with Yellow Cheese",
      description: "Crispy chicken, spicy sauce, pickles",
      image_url:
        "https://images.pexels.com/photos/8294896/pexels-photo-8294896.jpeg",
      price: 24.99,
      rating: 4.3,
      calories: 540,
      protein: 26,
      category_name: "Sandwiches",
      size: [{ name: "regular", price: 32.99, calories: 720, isDefault: true, protein : 50 }],
      customizations: [
        "Jalapeños",
        "Onions",
        "Fries",
        "Coke",
        "Choco Lava Cake",
      ],
    },
    {
      name: "Classic Margherita Pizza",
      description: "Tomato, mozzarella, fresh basil",
      image_url:
        "https://images.pexels.com/photos/31450853/pexels-photo-31450853.jpeg",
      price: 26.99,
      rating: 4.1,
      calories: 590,
      protein: 21,
      category_name: "Pizzas",
      size: [
        { name: "small", price: 25.99, calories: 490, isDefault: true, protein : 50  },
        { name: "medium", price: 30.99, calories: 890, isDefault: false, protein : 50  },
        { name: "large", price: 34.99, calories: 1190, isDefault: false, protein : 50  },
      ],
      customizations: ["Extra Cheese", "Olives", "Coke", "Garlic Bread"],
    },
    {
      name: "Malai Botti Pizza",
      description: "Mayo chicken, and loads of cheese",
      image_url:
        "https://images.pexels.com/photos/10371465/pexels-photo-10371465.jpeg",
      price: 29.99,
      rating: 4.8,
      calories: 580,
      protein: 38,
      category_name: "Bowls",
      size: [
        { name: "small", price: 25.99, calories: 490, isDefault: true, protein : 50  },
        { name: "medium", price: 30.99, calories: 890, isDefault: false, protein : 50  },
        { name: "large", price: 34.99, calories: 1190, isDefault: false, protein : 50  },
      ],
      customizations: ["Avocado", "Salad", "Sweet Corn", "Iced Tea"],
    },
    {
      name: "Paneer Momos with Chutney",
      description: "Paneer cubes, spicy masala, chutney,",
      image_url:
        "https://images.pexels.com/photos/28445589/pexels-photo-28445589.jpeg",
      price: 24.99,
      rating: 4.2,
      calories: 510,
      protein: 22,
      category_name: "Burritos",
      size: [
        { name: "small", price: 25.99, calories: 490, isDefault: true, protein : 50  },
        { name: "medium", price: 30.99, calories: 890, isDefault: false, protein : 50  },
        { name: "large", price: 34.99, calories: 1190, isDefault: false, protein : 50  },
      ],
      customizations: ["Jalapeños", "Fries", "Garlic Bread", "Coke"],
    },
    {
      name: "Chicken Club Sandwich",
      description: "Grilled chicken, lettuce, cheese, tomato",
      image_url:
        "https://images.pexels.com/photos/29346178/pexels-photo-29346178.jpeg",
      price: 27.49,
      rating: 4.5,
      calories: 610,
      protein: 31,
      category_name: "Sandwiches",
      size: [
        { name: "small", price: 25.99, calories: 490, isDefault: true, protein : 50  },
        { name: "medium", price: 30.99, calories: 890, isDefault: false, protein : 50  },
        { name: "large", price: 34.99, calories: 1190, isDefault: false, protein : 50  },
      ],
      customizations: ["Bacon", "Tomatoes", "Garlic Bread", "Iced Tea"],
    },
  ],
};

export default seedbaleData;
