export interface MenuItem {
  name: string;
  description: string;
  image_url: string;
  price: number;
  rating: number;
  calories: number;
  protein: number;
  category_name: string;
  customizations: string[];
  size: string[];
}

// ─── Image URL Map (Unsplash) ──────────────────────────────────────────────
const IMG = {
  pizza:        "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
  pizzaBbq:     "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
  pizzaCheese:  "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
  pizzaVeg:     "https://images.unsplash.com/photo-1528137871618-79d2761e3fd5?w=800&q=80",
  pizzaSpicy:   "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=800&q=80",
  burger:       "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
  burgerCheese: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&q=80",
  burgerGrill:  "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  burgerDouble: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&q=80",
  shawarma:     "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80",
  parathaRoll:  "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&q=80",
  biryani:      "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80",
  pulao:        "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=80",
  karahi:       "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&q=80",
  handi:        "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=800&q=80",
  dal:          "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
  naan:         "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80",
  soup:         "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  salad:        "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
  fries:        "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=800&q=80",
  wings:        "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&q=80",
  nuggets:      "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80",
  tikka:        "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80",
  noodles:      "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80",
};

export const menuItems: MenuItem[] = [
  // ─── PIZZAS ───────────────────────────────────────────────────────────────
  {
    name: "Pizza Fajita",
    description: "Chicken, Bell Pepper, Onion on a crispy base",
    image_url: IMG.pizza,
    price: 780,
    rating: 4.5,
    calories: 720,
    protein: 32,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Cheese", "Extra Chicken", "Thin Crust"],
  },
  {
    name: "Pizza B.B.Q",
    description: "Chicken Boti, Bell Pepper, Onions, Tomato with smoky BBQ sauce",
    image_url: IMG.pizzaBbq,
    price: 750,
    rating: 4.6,
    calories: 780,
    protein: 35,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Cheese", "Extra Boti", "Thin Crust"],
  },
  {
    name: "Special Grill Pizza",
    description: "Grilled chicken with mixed vegetables and special sauce",
    image_url: IMG.pizza,
    price: 850,
    rating: 4.7,
    calories: 800,
    protein: 38,
    category_name: "Pizzas",
    size: ["Medium", "Large"],
    customizations: ["Extra Cheese", "Extra Grilled Chicken"],
  },
  {
    name: "Lahori Special Pizza",
    description: "Spicy Lahori-style pizza with desi masala and chicken",
    image_url: IMG.pizzaSpicy,
    price: 900,
    rating: 4.7,
    calories: 850,
    protein: 36,
    category_name: "Pizzas",
    size: ["Medium", "Large"],
    customizations: ["Extra Spicy", "Extra Cheese"],
  },
  {
    name: "Crazy Crust Pizza",
    description: "Stuffed crust pizza loaded with cheese and toppings",
    image_url: IMG.pizzaCheese,
    price: 900,
    rating: 4.5,
    calories: 920,
    protein: 34,
    category_name: "Pizzas",
    size: ["Medium", "Large"],
    customizations: ["Extra Cheese", "Extra Toppings"],
  },
  {
    name: "Pizza Club Supreme",
    description: "Onion, Bell Pepper, Tomato, Olives, Mushroom, Corn, Sausage, Pepperoni",
    image_url: IMG.pizzaBbq,
    price: 900,
    rating: 4.8,
    calories: 950,
    protein: 40,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Cheese", "Extra Pepperoni"],
  },
  {
    name: "Pizza Cheese Lover",
    description: "Onion, Bell Pepper, Pineapple, Tomato, Sweet Corn with Double Cheese",
    image_url: IMG.pizzaCheese,
    price: 850,
    rating: 4.6,
    calories: 880,
    protein: 30,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Cheese", "No Pineapple"],
  },
  {
    name: "Cheese Pizza",
    description: "Classic pizza topped with only mozzarella cheese",
    image_url: IMG.pizzaCheese,
    price: 700,
    rating: 4.4,
    calories: 650,
    protein: 22,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Cheese", "Thin Crust"],
  },
  {
    name: "Pizza Flavourz Special",
    description: "Chef's signature pizza with a unique blend of toppings",
    image_url: IMG.pizza,
    price: 800,
    rating: 4.9,
    calories: 860,
    protein: 36,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Cheese", "Extra Toppings"],
  },
  {
    name: "Pizza Vegetarian",
    description: "Fresh vegetables, bell peppers, mushrooms, corn on a seasoned base",
    image_url: IMG.pizzaVeg,
    price: 750,
    rating: 4.3,
    calories: 580,
    protein: 18,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Cheese", "Extra Veggies", "No Onion"],
  },
  {
    name: "Pizza Hot & Spicy",
    description: "Fiery hot pizza loaded with spicy chicken and jalapeños",
    image_url: IMG.pizzaSpicy,
    price: 850,
    rating: 4.5,
    calories: 820,
    protein: 34,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Spicy", "Extra Cheese"],
  },
  {
    name: "Chicken Tandoori Pizza",
    description: "Tandoori marinated chicken chunks on a spiced tomato base",
    image_url: IMG.pizza,
    price: 850,
    rating: 4.7,
    calories: 840,
    protein: 38,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Chicken", "Extra Cheese"],
  },
  {
    name: "Chicken Punjabi Pickle",
    description: "Pickle-marinated chicken with onion, tomato, green chilli, olive",
    image_url: IMG.pizzaSpicy,
    price: 750,
    rating: 4.6,
    calories: 800,
    protein: 36,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Pickle", "Extra Cheese"],
  },
  {
    name: "Chicken Mushroom Pizza",
    description: "Chicken, Mushroom, Green Chilli, Onion on a creamy base",
    image_url: IMG.pizzaVeg,
    price: 700,
    rating: 4.5,
    calories: 760,
    protein: 33,
    category_name: "Pizzas",
    size: ["Small", "Medium", "Large"],
    customizations: ["Extra Mushroom", "Extra Cheese"],
  },
  {
    name: "Behari Kabab Pizza",
    description: "Juicy Behari kabab strips on a spiced pizza base",
    image_url: IMG.pizzaBbq,
    price: 950,
    rating: 4.8,
    calories: 900,
    protein: 42,
    category_name: "Pizzas",
    size: ["Medium", "Large"],
    customizations: ["Extra Kabab", "Extra Cheese"],
  },
  {
    name: "Malai Raja Pizza",
    description: "Creamy malai chicken with rich white sauce and premium toppings",
    image_url: IMG.pizzaCheese,
    price: 1000,
    rating: 4.9,
    calories: 980,
    protein: 44,
    category_name: "Pizzas",
    size: ["Medium", "Large"],
    customizations: ["Extra Malai Chicken", "Extra Cheese"],
  },

  // ─── SHAWARMA ─────────────────────────────────────────────────────────────
  {
    name: "Chicken Shawarma",
    description: "Classic chicken shawarma with garlic sauce and fresh salad",
    image_url: IMG.shawarma,
    price: 140,
    rating: 4.3,
    calories: 420,
    protein: 28,
    category_name: "Shawarma",
    size: ["Regular"],
    customizations: ["No Salad", "Extra Garlic Sauce", "Extra Chicken"],
  },
  {
    name: "Chicken Shawarma Without Salad",
    description: "Tender chicken shawarma without salad, extra sauce",
    image_url: IMG.shawarma,
    price: 200,
    rating: 4.3,
    calories: 390,
    protein: 28,
    category_name: "Shawarma",
    size: ["Regular"],
    customizations: ["Extra Garlic Sauce", "Extra Chicken", "Spicy"],
  },
  {
    name: "Chicken Shawarma Extra Cheese",
    description: "Chicken shawarma loaded with extra melted cheese",
    image_url: IMG.shawarma,
    price: 220,
    rating: 4.5,
    calories: 480,
    protein: 30,
    category_name: "Shawarma",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Chicken", "Spicy"],
  },
  {
    name: "Zinger Shawarma",
    description: "Crispy zinger-style chicken shawarma with tangy sauce",
    image_url: IMG.shawarma,
    price: 250,
    rating: 4.6,
    calories: 500,
    protein: 32,
    category_name: "Shawarma",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "Spicy"],
  },
  {
    name: "Supreme Shawarma",
    description: "Premium shawarma with multiple fillings and special sauce",
    image_url: IMG.shawarma,
    price: 410,
    rating: 4.8,
    calories: 620,
    protein: 40,
    category_name: "Shawarma",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Chicken", "Extra Sauce"],
  },
  {
    name: "Mayo Shawarma",
    description: "Classic shawarma with creamy mayo dressing",
    image_url: IMG.shawarma,
    price: 200,
    rating: 4.2,
    calories: 450,
    protein: 26,
    category_name: "Shawarma",
    size: ["Regular"],
    customizations: ["Extra Mayo", "Extra Chicken", "No Salad"],
  },
  {
    name: "Plater Shawarma",
    description: "Shawarma platter served with fries and dipping sauces",
    image_url: IMG.shawarma,
    price: 350,
    rating: 4.5,
    calories: 700,
    protein: 38,
    category_name: "Shawarma",
    size: ["Regular"],
    customizations: ["Extra Fries", "Extra Sauce", "Extra Chicken"],
  },

  // ─── BURGERS ──────────────────────────────────────────────────────────────
  {
    name: "Chicken Burger",
    description: "Classic crispy chicken burger with fresh lettuce and tomato",
    image_url: IMG.burger,
    price: 220,
    rating: 4.3,
    calories: 480,
    protein: 28,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "No Lettuce", "Fries", "Coke"],
  },
  {
    name: "Chicken Burger with Cheese",
    description: "Juicy chicken burger topped with melted cheese",
    image_url: IMG.burgerCheese,
    price: 280,
    rating: 4.5,
    calories: 560,
    protein: 32,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "Fries", "Coke"],
  },
  {
    name: "Karamza Burger",
    description: "Special Karamza-style burger with unique seasoning",
    image_url: IMG.burger,
    price: 280,
    rating: 4.4,
    calories: 540,
    protein: 30,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "Fries"],
  },
  {
    name: "Zinger Burger Crispy",
    description: "Extra crispy zinger fillet with spicy mayo and coleslaw",
    image_url: IMG.burgerCheese,
    price: 250,
    rating: 4.6,
    calories: 590,
    protein: 33,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Crispy", "Extra Cheese", "Fries", "Coke"],
  },
  {
    name: "Zinger Pizza Burger",
    description: "Fusion burger with zinger fillet and pizza sauce topped with cheese",
    image_url: IMG.burgerGrill,
    price: 500,
    rating: 4.7,
    calories: 720,
    protein: 38,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "Fries", "Coke"],
  },
  {
    name: "Zinger Burger With Cheese",
    description: "Classic zinger burger loaded with extra cheese",
    image_url: IMG.burgerCheese,
    price: 300,
    rating: 4.5,
    calories: 630,
    protein: 34,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "Fries"],
  },
  {
    name: "Double Dekker Burger",
    description: "Double patty stacked burger with all the classic toppings",
    image_url: IMG.burgerDouble,
    price: 500,
    rating: 4.8,
    calories: 860,
    protein: 50,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Patty", "Fries", "Coke"],
  },
  {
    name: "Grill Burger",
    description: "Flame-grilled chicken burger with smoky flavour",
    image_url: IMG.burgerGrill,
    price: 300,
    rating: 4.5,
    calories: 520,
    protein: 35,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "Fries"],
  },
  {
    name: "Chicken Hot Shot",
    description: "Spicy hot chicken burger with fiery sauce and jalapeños",
    image_url: IMG.burger,
    price: 500,
    rating: 4.6,
    calories: 680,
    protein: 36,
    category_name: "Burgers",
    size: ["Regular"],
    customizations: ["Extra Spicy", "Extra Cheese", "Fries", "Coke"],
  },

  // ─── PARATHA ROLL ─────────────────────────────────────────────────────────
  {
    name: "Chicken Paratha Roll",
    description: "Soft paratha wrapped with spiced chicken and salad",
    image_url: IMG.parathaRoll,
    price: 150,
    rating: 4.3,
    calories: 420,
    protein: 26,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["No Salad", "Extra Chicken", "Extra Sauce", "Spicy"],
  },
  {
    name: "Chicken Paratha Roll Without Salad",
    description: "Paratha roll with chicken filling, no salad",
    image_url: IMG.parathaRoll,
    price: 230,
    rating: 4.2,
    calories: 400,
    protein: 26,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra Chicken", "Extra Sauce", "Spicy"],
  },
  {
    name: "Chicken Paratha Roll With Cheese",
    description: "Paratha roll stuffed with chicken and melted cheese",
    image_url: IMG.parathaRoll,
    price: 230,
    rating: 4.4,
    calories: 480,
    protein: 28,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Chicken", "Spicy"],
  },
  {
    name: "Mayo Paratha Roll",
    description: "Paratha roll with chicken and creamy mayo dressing",
    image_url: IMG.parathaRoll,
    price: 210,
    rating: 4.3,
    calories: 450,
    protein: 24,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra Mayo", "Extra Chicken", "No Salad"],
  },
  {
    name: "Chicken B.B.Q Roll",
    description: "BBQ-flavoured chicken wrapped in a crispy paratha",
    image_url: IMG.parathaRoll,
    price: 250,
    rating: 4.5,
    calories: 470,
    protein: 30,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra BBQ Sauce", "Extra Chicken", "Spicy"],
  },
  {
    name: "Chicken Mirchi Roll",
    description: "Spicy chilli chicken paratha roll with green chillies",
    image_url: IMG.parathaRoll,
    price: 250,
    rating: 4.4,
    calories: 440,
    protein: 28,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra Spicy", "Extra Chilli", "Extra Chicken"],
  },
  {
    name: "Zinger Paratha Roll",
    description: "Crispy zinger chicken fillet wrapped in fresh paratha",
    image_url: IMG.parathaRoll,
    price: 260,
    rating: 4.6,
    calories: 520,
    protein: 32,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra Cheese", "Extra Sauce", "Spicy"],
  },
  {
    name: "Malai Boti Roll",
    description: "Creamy malai boti chunks in a soft paratha roll",
    image_url: IMG.parathaRoll,
    price: 350,
    rating: 4.7,
    calories: 580,
    protein: 38,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra Malai Boti", "Extra Sauce", "Raita"],
  },
  {
    name: "Nuggets Roll",
    description: "Crispy chicken nuggets wrapped in a paratha roll",
    image_url: IMG.parathaRoll,
    price: 350,
    rating: 4.4,
    calories: 560,
    protein: 28,
    category_name: "Paratha Roll",
    size: ["Regular"],
    customizations: ["Extra Nuggets", "Extra Sauce", "Cheese"],
  },

  // ─── SIDES ────────────────────────────────────────────────────────────────
  {
    name: "Hot Wings",
    description: "Crispy hot wings with spicy coating, served with dip",
    image_url: IMG.wings,
    price: 450,
    rating: 4.6,
    calories: 680,
    protein: 45,
    category_name: "Sides",
    size: ["6 Pieces", "12 Pieces"],
    customizations: ["Extra Spicy", "BBQ Sauce", "Ranch Dip"],
  },
  {
    name: "Nuggets",
    description: "Golden crispy chicken nuggets with dipping sauce",
    image_url: IMG.nuggets,
    price: 500,
    rating: 4.5,
    calories: 540,
    protein: 32,
    category_name: "Sides",
    size: ["10 Pieces"],
    customizations: ["Ketchup", "BBQ Sauce", "Mayo Dip"],
  },
  {
    name: "French Fries",
    description: "Crispy golden french fries seasoned with salt",
    image_url: IMG.fries,
    price: 280,
    rating: 4.4,
    calories: 380,
    protein: 6,
    category_name: "Sides",
    size: ["Regular", "Large"],
    customizations: ["Extra Salt", "Ketchup", "Cheese Sauce", "Spicy"],
  },
  {
    name: "Family French Fries",
    description: "Large sharing portion of crispy seasoned fries",
    image_url: IMG.fries,
    price: 480,
    rating: 4.4,
    calories: 760,
    protein: 12,
    category_name: "Sides",
    size: ["Family"],
    customizations: ["Extra Salt", "Ketchup", "Cheese Sauce", "Spicy"],
  },

  // ─── TANDOOR ──────────────────────────────────────────────────────────────
  {
    name: "Chicken Naan",
    description: "Freshly baked naan topped with spiced minced chicken",
    image_url: IMG.naan,
    price: 150,
    rating: 4.5,
    calories: 380,
    protein: 22,
    category_name: "Tandoor",
    size: ["Regular"],
    customizations: ["Extra Chicken", "Raita", "Butter"],
  },
  {
    name: "Ginger Naan",
    description: "Soft naan infused with fresh ginger flavour",
    image_url: IMG.naan,
    price: 60,
    rating: 4.2,
    calories: 220,
    protein: 7,
    category_name: "Tandoor",
    size: ["Regular"],
    customizations: ["Butter", "Extra Ginger"],
  },
  {
    name: "Garlic Naan",
    description: "Classic garlic naan with butter and fresh garlic",
    image_url: IMG.naan,
    price: 60,
    rating: 4.4,
    calories: 230,
    protein: 7,
    category_name: "Tandoor",
    size: ["Regular"],
    customizations: ["Extra Butter", "Extra Garlic"],
  },
  {
    name: "Tandoori Roti",
    description: "Traditional clay oven baked whole wheat roti",
    image_url: IMG.naan,
    price: 25,
    rating: 4.0,
    calories: 160,
    protein: 5,
    category_name: "Tandoor",
    size: ["Regular"],
    customizations: ["Butter", "Plain"],
  },

  // ─── SALADS ───────────────────────────────────────────────────────────────
  {
    name: "Flavourz Special Salad",
    description: "House special salad with fresh greens and signature dressing",
    image_url: IMG.salad,
    price: 450,
    rating: 4.4,
    calories: 220,
    protein: 8,
    category_name: "Salads",
    size: ["Regular"],
    customizations: ["Extra Dressing", "No Onion", "Extra Croutons"],
  },
  {
    name: "Green Salad",
    description: "Fresh garden greens with house vinaigrette",
    image_url: IMG.salad,
    price: 100,
    rating: 4.0,
    calories: 120,
    protein: 4,
    category_name: "Salads",
    size: ["Regular"],
    customizations: ["Extra Dressing", "No Onion"],
  },
  {
    name: "Raita",
    description: "Chilled yoghurt with cucumber, mint and spices",
    image_url: IMG.salad,
    price: 40,
    rating: 4.2,
    calories: 80,
    protein: 4,
    category_name: "Salads",
    size: ["Small", "Large"],
    customizations: ["Extra Mint", "Spicy"],
  },

  // ─── SOUP ─────────────────────────────────────────────────────────────────
  {
    name: "Chicken Corn Soup",
    description: "Creamy chicken soup with sweet corn and egg drops",
    image_url: IMG.soup,
    price: 320,
    rating: 4.4,
    calories: 240,
    protein: 16,
    category_name: "Soup",
    size: ["Small", "Large"],
    customizations: ["Extra Chicken", "Spicy", "Extra Corn"],
  },
  {
    name: "Hot & Sour Soup",
    description: "Tangy spicy soup with vegetables and chicken",
    image_url: IMG.soup,
    price: 240,
    rating: 4.3,
    calories: 180,
    protein: 12,
    category_name: "Soup",
    size: ["Small", "Large"],
    customizations: ["Extra Spicy", "Extra Sour", "Extra Chicken"],
  },
  {
    name: "Lemon Coriander Soup",
    description: "Light and refreshing soup with lemon and fresh coriander",
    image_url: IMG.soup,
    price: 220,
    rating: 4.2,
    calories: 140,
    protein: 8,
    category_name: "Soup",
    size: ["Small", "Large"],
    customizations: ["Extra Lemon", "Extra Coriander"],
  },

  // ─── STARTERS ─────────────────────────────────────────────────────────────
  {
    name: "Flavourz Special Chicken Starter",
    description: "Chef's signature platter of crispy chicken bites",
    image_url: IMG.tikka,
    price: 800,
    rating: 4.7,
    calories: 560,
    protein: 38,
    category_name: "Starters",
    size: ["Regular"],
    customizations: ["Extra Spicy", "Mint Dip", "Ketchup"],
  },
  {
    name: "Chicken Tikka",
    description: "Tender marinated chicken tikka grilled to perfection",
    image_url: IMG.tikka,
    price: 800,
    rating: 4.8,
    calories: 480,
    protein: 42,
    category_name: "Starters",
    size: ["Half", "Full"],
    customizations: ["Extra Spicy", "Raita", "Naan"],
  },
  {
    name: "Dahi Chicken",
    description: "Yoghurt-marinated chicken starter with mint chutney",
    image_url: IMG.tikka,
    price: 750,
    rating: 4.6,
    calories: 440,
    protein: 38,
    category_name: "Starters",
    size: ["Half", "Full"],
    customizations: ["Extra Raita", "Mint Chutney", "Naan"],
  },

  // ─── CHICKEN DISHES ───────────────────────────────────────────────────────
  {
    name: "Chicken Karahi",
    description: "Spicy chicken cooked in a wok with tomatoes, ginger and chillies",
    image_url: IMG.karahi,
    price: 1280,
    rating: 4.8,
    calories: 620,
    protein: 48,
    category_name: "Chicken",
    size: ["Half", "Full"],
    customizations: ["Extra Spicy", "Naan", "Roti", "Extra Ginger"],
  },
  {
    name: "Chicken Handi",
    description: "Slow-cooked creamy chicken handi with aromatic spices",
    image_url: IMG.handi,
    price: 1180,
    rating: 4.7,
    calories: 580,
    protein: 44,
    category_name: "Chicken",
    size: ["Half", "Full"],
    customizations: ["Extra Gravy", "Naan", "Roti"],
  },

  // ─── MUTTON DISHES ────────────────────────────────────────────────────────
  {
    name: "Mutton Karahi",
    description: "Tender mutton pieces cooked in a spicy karahi masala",
    image_url: IMG.karahi,
    price: 2340,
    rating: 4.9,
    calories: 720,
    protein: 52,
    category_name: "Mutton",
    size: ["Half", "Full"],
    customizations: ["Extra Spicy", "Naan", "Roti", "Extra Ginger"],
  },
  {
    name: "Mutton Handi",
    description: "Rich and creamy mutton handi with slow-cooked spices",
    image_url: IMG.handi,
    price: 2280,
    rating: 4.8,
    calories: 680,
    protein: 50,
    category_name: "Mutton",
    size: ["Half", "Full"],
    customizations: ["Extra Gravy", "Naan", "Roti"],
  },

  // ─── PAKISTANI RICE ───────────────────────────────────────────────────────
  {
    name: "Special Chicken Biryani",
    description: "Aromatic basmati rice layered with spiced chicken and saffron",
    image_url: IMG.biryani,
    price: 500,
    rating: 4.7,
    calories: 680,
    protein: 38,
    category_name: "Pakistani Rice",
    size: ["Plate", "Half", "Full"],
    customizations: ["Extra Chicken", "Raita", "Salad", "Extra Spicy"],
  },
  {
    name: "Mutton Biryani",
    description: "Slow-cooked mutton biryani with whole spices and caramelised onions",
    image_url: IMG.biryani,
    price: 700,
    rating: 4.8,
    calories: 780,
    protein: 44,
    category_name: "Pakistani Rice",
    size: ["Plate", "Half", "Full"],
    customizations: ["Extra Mutton", "Raita", "Salad"],
  },
  {
    name: "Chicken Pulao",
    description: "Fragrant chicken pulao with whole spices and tender chicken",
    image_url: IMG.pulao,
    price: 530,
    rating: 4.5,
    calories: 620,
    protein: 34,
    category_name: "Pakistani Rice",
    size: ["Plate", "Half", "Full"],
    customizations: ["Extra Chicken", "Raita", "Salad"],
  },
  {
    name: "Mutton Pulao",
    description: "Traditional mutton pulao slow cooked with aromatic spices",
    image_url: IMG.pulao,
    price: 700,
    rating: 4.7,
    calories: 720,
    protein: 42,
    category_name: "Pakistani Rice",
    size: ["Plate", "Half", "Full"],
    customizations: ["Extra Mutton", "Raita", "Salad"],
  },

  // ─── VEGETABLE + DAL ──────────────────────────────────────────────────────
  {
    name: "Shahi Dal",
    description: "Rich and creamy royal lentil curry with butter and cream",
    image_url: IMG.dal,
    price: 320,
    rating: 4.4,
    calories: 320,
    protein: 16,
    category_name: "Vegetable & Dal",
    size: ["Half", "Full"],
    customizations: ["Extra Butter", "Naan", "Roti"],
  },
  {
    name: "Dal Mash",
    description: "Classic white lentil dal tempered with onion and spices",
    image_url: IMG.dal,
    price: 220,
    rating: 4.3,
    calories: 280,
    protein: 14,
    category_name: "Vegetable & Dal",
    size: ["Half", "Full"],
    customizations: ["Extra Tarka", "Naan", "Roti"],
  },



  
  {
    name: "Flavourz Special Chinese",
    description: "Chef's signature Chinese platter with noodles and stir-fried chicken",
    image_url: IMG.noodles,
    price: 550,
    rating: 4.5,
    calories: 640,
    protein: 34,
    category_name: "Chinese",
    size: ["Regular"],
    customizations: ["Extra Spicy", "Extra Sauce", "Extra Chicken"],
  },
  {
    name: "Chicken Chowmein",
    description: "Stir-fried noodles with chicken and vegetables in soy sauce",
    image_url: IMG.noodles,
    price: 550,
    rating: 4.4,
    calories: 580,
    protein: 30,
    category_name: "Chinese",
    size: ["Regular", "Large"],
    customizations: ["Extra Spicy", "Extra Chicken", "Extra Vegetables"],
  },
];